### ISSUE TITLE
Runtime Values (Reflection) not working in 02.03.02

### ISSUE THREAD

**Issue by djamell** [kevinmschreiner/OpenWebStudio#3]
Clean install of DNN 9.6.1 and OWS 02.03.02.

Building a "Contact Us" Form, I like to get the IP Address of the user submitting the form and did so in the past in OWS by adding [Request.UserHostAddress] somewhere in the Email that gets sent.

When I add [Request.UserHostAddress] to the body of an Email, it does not return the IP Address.  It just adds the token.

This used to work a long time ago, hasn't in several DNN Versions.  I'm guessing DNN did something to break this.

Can you get this hooked in again?

**Comment by kevinmschreiner** [comment]
Yep, I'll take a look

**Comment by kevinmschreiner** [comment]
While developing the release for the 9.6.2 build, I was able to identify the cause of the problem. The issue is not actually with OWS, but rather the web.config. OWS must run in Full Trust mode in order to allow for Reflection. When in low or medium-trust, which is what DNN transitioned into years ago, Reflection is not a permission that is allowed. 

If you do not want to allow the entire application to execute in Full Trust, you can manually add the necessary security permission. Rick Strahl provides a pretty simple explanation of setting that up here: [(https://weblog.west-wind.com/posts/2006/Jul/10/Running-ASPNET-in-Medium-Trust)]
